### ISSUE TITLE
the code error in azure China

### ISSUE THREAD

**Issue by orgjava** [microsoftgraph/aspnet-connect-rest-sample#15]
the code error in azure China

**Comment by DianeD** [comment]
Hi @orgjava . This version of the sample won't work with Azure China because it uses the Azure AD v2.0 endpoint and registration process. 
You should be able to use the [last_v1_auth version](https://github.com/microsoftgraph/aspnet-connect-rest-sample/releases), following the instructions in that version's readme to register it on the Azure China [portal](http://manage.windowsazure.cn/).

**Comment by DianeD** [comment]
Hi @orgjava . Assuming this issue is resolved. Please reopen if you're still having problems!
