### ISSUE TITLE
Log in does not seem to persist

### ISSUE THREAD

**Issue by metro-mark** [microsoftgraph/aspnet-connect-rest-sample#25]
Load the project in visual studio, run, login, close the browser and reopen it. I am prompted to log in again.

**Comment by jamescro** [comment]
This is by design the authentication code in this sample is simple and doesn't currently look for a previously stored access token before launching the authentication UI. https://github.com/azure-samples has other examples of authentication code to which you can refer when you want to do more advanced sorts of authentication operations.
