### ISSUE TITLE
An error occurred while processing your request. unsupported_response_type

### ISSUE THREAD

**Issue by kuntoro-adi** [microsoftgraph/aspnet-connect-rest-sample#29]
Hi,

I got an error "unsupported_response_type". I already put the appId and appSecret on the Web.config. When the "Sign in with Microsoft" clicked, it redirected to Microsoft login page https://login.microsoftonline.com/common/oauth2/v2.0/. However, after e-mail field was filled, it redirected to the app home page with unsupported_response_type error. As suggested by other source, I already tried to add "/signin-microsoft" on the redirect URL, but doesn't work.

Thank you very much.

**Comment by jamescro** [comment]
You might see that error if your client isn't correctly configured. Did you use the app registration portal (https://apps.dev.microsoft.com/) instead of the Azure portal to register your client? And did you add the Web platform and redirect URI to the client? Sometimes people forget to save changes and updates after they've added the Web platform, and that can lead to this problem.

**Comment by kuntoro-adi** [comment]
I don't know what triggered the error at my first attempt. 
However, I generated the solution file via https://developer.microsoft.com/en-us/graph/quick-start and it works fine. 
Thank you @jamescro
