### ISSUE TITLE
The user or administrator has not consented to use the application with ID

### ISSUE THREAD

**Issue by FractalPaul** [microsoftgraph/aspnet-connect-rest-sample#33]
Hello, I'm trying this example out to connect to my Azure AD App Registered account.  I already have the necessary permissions granted by the administrator.

1. When I try this example right out of the box I get the error: "Application ... is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint."
1. So, to get around this I added the AADInstance value to the ConfidentialClientApplication constructor (2nd argument for Authority)  that then gets me to the next error: "Message=AADSTS65001: The user or administrator has not consented to use the application with ID '...' named '...ToolSuite.Debug'. Send an interactive authorization request for this user and resource."  

So, I understand that the user needs to consent to the usage but how do I do that through the code?  I've read about using the parameter: "?prompt=admin_consent" but where do I put that?  I've tried putting it on the Authority parameter but see that it get truncated before making the AcquireToken…  call.  How do I proceed?

Also, is the correct way to get access to Azure AD and Microsoft Graph API.  I'm trying to get a list of the Azure AD Groups that the User belongs to.  I see the GUIDs that return for the signed in user but that is all the information I get.  Trying to get more information about the Groups. Thanks for you help.

**Comment by jasonjoh** [comment]
A few things here.

- For 1, I don't reproduce this. Did you register the app per the instructions in the README? I'm trying to understand what you mean by "Azure AD App Registered account".
- For 2, I also don't reproduce this.

This sample does not require admin consent as-is. The user consents during the sign-in process. When you click the sign-in button, you should get redirected to login.microsoftonline.com. After providing username/pass, you should see a screen like this (the consent screen):

![image](https://user-images.githubusercontent.com/8966342/40843424-e44ecca0-657e-11e8-8712-fa465bd8137f.png)

You'll only see this once. Once you consent, AAD records that for you so you don't have to be prompted again.

Finally, you asked about getting access to the Azure AD via Graph. This sample can start you down that path, but it doesn't do it as-is. The necessary permissions to list groups DO require admin consent, so maybe what you're seeing is because you've modified the sample to request additional scopes?

**Comment by jasonjoh** [comment]
Closing as no response.
